[package]
name = "sonm-gateway"
version = "0.1.0"
license = "AGPL-3.0-or-later"
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# util
log = { workspace = true }
sentry = { workspace = true }
lru = { workspace = true }
ulid = { workspace = true }
once_cell = { workspace = true }
redis-kiss = { workspace = true, default-features = false, features = [
    "tokio-runtime",
] }
lru_time_cache = { workspace = true }
async-channel = { workspace = true }

# parsing
querystring = { workspace = true }
regex = { workspace = true }

# serde
bincode = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }

# async
futures = { workspace = true }
async-tungstenite = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { workspace = true, features = ["compat"] }

# core
sonm-result = { workspace = true }
sonm-models = { workspace = true }
sonm-config = { workspace = true }
sonm-database = { workspace = true, features = ["voice"] }
sonm-permissions = { workspace = true }
sonm-presence = { workspace = true, features = ["redis-is-patched"] }

# redis
fred = { workspace = true, features = ["subscriber-client"] }
