[package]
name = "sonm-ratelimits"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Zomatree <me@zomatree.live>", "Paul Makles <me@insrt.uk>"]
description = "Sonm: Ratelimit Handler"
repository = "https://github.com/krynce/sonm-backend"

[features]
rocket = [
    "dep:rocket",
    "dep:revolt_rocket_okapi",
    "sonm-database/rocket-impl",
]
axum = ["dep:axum", "sonm-database/axum-impl"]

default = ["rocket", "axum"]

[dependencies]
sonm-database = { workspace = true }
sonm-result = { workspace = true }
sonm-config = { workspace = true }

rocket = { workspace = true, optional = true }
revolt_rocket_okapi = { workspace = true, optional = true }

axum = { workspace = true, optional = true, features = ["macros"] }

redis-kiss = { workspace = true }

serde = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
